"""Generate ui/metrics.lua: real advance widths for the panel's font.

    python tools/genmetrics.py

Reads the installed TrueType files and writes the advance width of every
printable ASCII character as a fraction of the em, so the table is
size-independent: pixels = em_fraction * points * 96/72.

Why the table is shipped rather than measured at runtime. The panel needs to know
how wide a string will be before it draws it, in order to wrap and truncate.
windower.text.get_extents only answers about a string an object has already been
given, which is a frame too late, and it cannot answer at all for a string the
panel decided not to draw. Monospace hid this problem behind one number per size;
proportional type does not.

Measured at 400px and divided by the em rather than measured at the target size,
because the rasteriser rounds each advance to whole pixels at small sizes and the
rounding error is what the 2% slack in metrics.lua covers.
"""

import io
import os
import sys

try:
    from PIL import ImageFont
except ImportError:
    sys.exit("needs Pillow:  python -m pip install Pillow")

SIZE = 400

HERE = os.path.dirname(os.path.abspath(__file__))

#[ The system font directory, from the environment rather than hardcoded: Windows
#  is not always on C:, and a path with a drive letter in it is a path that runs
#  on one machine.
#
#  The literal is a last resort and not an expectation. Windows always sets
#  SystemRoot, so the fallback is reached only off Windows, and what it buys
#  there is that main() names a font it cannot find instead of the environment
#  lookup raising KeyError with no path in it. ]
FONTDIR = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "Fonts")
FONTS = {
    "regular": os.path.join(FONTDIR, "segoeui.ttf"),
    "bold": os.path.join(FONTDIR, "segoeuib.ttf"),
}
OUT = os.path.normpath(os.path.join(HERE, "..", "ui", "metrics.lua"))

HEADER = '''--[[
ui/metrics.lua -- advance widths for the panel's font, as fractions of the em.

GENERATED by tools/genmetrics.py from the installed TrueType files. Do not edit
by hand; regenerate.

Why it exists. Proportional type has no single advance number, and
`windower.text.get_extents` cannot carry layout: it only answers about a string
an object has already been given, which is a frame too late to decide how to wrap
that string, and it cannot answer at all about a string you have not drawn.

Indexed by byte, 32..126, because the panel is single-byte ASCII only: Windower's
text rendering does not handle UTF-8 multibyte. A byte outside that range falls
through the metatable to the average advance, so a stray character costs a
slightly wrong wrap and never an error.

Measured, not estimated. Segoe UI Regular averages 0.5136 em across printable
ASCII and Consolas averages 0.5498, so a monospace constant taken from Consolas
over-estimates every proportional string by about 7%. That direction only wastes
space; the units error is the one that runs text off the panel.
]]

local M = {}

M.PT_TO_PX = 96 / 72

'''

FOOTER = '''
local function guard(t, avg)
    return setmetatable(t, {__index = function() return avg end})
end
guard(M.regular, M.avg_regular)
guard(M.bold, M.avg_bold)

--[[ Width of `s` in pixels at `pt` points.

     The 2% slack covers hinting. The rasteriser rounds each glyph advance to a
     whole pixel at screen sizes, and over 50 characters those roundings do not
     cancel. Over-estimating is the safe direction: it wraps a word one early,
     where under-estimating runs text off the panel. ]]
function M.width(s, pt, bold)
    if type(s) ~= 'string' or s == '' then return 0 end
    local t = bold and M.bold or M.regular
    local sum = 0
    for i = 1, #s do sum = sum + t[s:byte(i)] end
    return sum * pt * M.PT_TO_PX * 1.02
end

--[[ How many characters of `s` fit in `px`. Walks the string rather than
     dividing by an average, because "Ill" and "WWW" are not the same width. ]]
function M.fit_count(s, pt, px, bold)
    local t = bold and M.bold or M.regular
    local k = pt * M.PT_TO_PX * 1.02
    local sum, n = 0, 0
    for i = 1, #s do
        sum = sum + t[s:byte(i)] * k
        if sum > px then return n end
        n = i
    end
    return n
end

--[[ Vertical geometry in pixels at a point size.

     `set_location` places text by the top of its line box. `ink_y` is how far
     below that the glyphs actually begin and `ink_height` is how tall they are,
     and together they are the rectangle to highlight or to hit-test. Size a
     hover band from the line pitch instead and it draws about seven pixels above
     its own text. ]]
function M.ink_y(pt)      return pt * M.PT_TO_PX * M.ink_top end
function M.ink_height(pt) return pt * M.PT_TO_PX * M.ink_h end
function M.line_height(pt) return pt * M.PT_TO_PX * M.line_h end

--[[ The y to draw at so the cap box is centred in a strip of height `h` starting
     at `y`. Cap-centred rather than ink-centred: most interface strings carry no
     descender, so centring the full ink box makes them ride visibly high. ]]
function M.center_y(y, h, pt)
    local em = pt * M.PT_TO_PX
    return math.floor(y + h / 2 - (M.cap_top + M.cap_h / 2) * em + 0.5)
end

--[[ Where an underline goes: just below the descender. ]]
function M.underline_y(y, pt)
    return math.floor(y + (M.ink_top + M.ink_h) * pt * M.PT_TO_PX + 0.5)
end

return M
'''


def table(name, font):
    """Emit with explicit byte indices.

    A Lua array literal is 1-indexed while the lookup is by byte value, so the
    array form makes width('M') return the advance of 'i': off by 31, silently,
    and in the direction that makes wide strings measure narrow. Explicit keys
    cost file size and remove the whole class of error.
    """
    vals = {c: font.getlength(chr(c)) / SIZE for c in range(32, 127)}
    rows = []
    for base in range(32, 127, 8):
        chunk = list(range(base, min(base + 8, 127)))
        rows.append("    " + " ".join("[%d]=%.4f," % (c, vals[c]) for c in chunk))
    return ("M." + name + " = {\n" + "\n".join(rows) + "\n}\n",
            sum(vals.values()) / len(vals))


def vmetrics(font):
    """Vertical geometry, as fractions of the em.

    windower.text.set_location places text by the top of its line box, not by
    the top of the glyphs, so anything that has to line up with what the eye
    sees, such as a hover band, a hit target or vertical centring, needs to know
    how far below that the ink actually starts. Guess it, and a hover band sized
    from the line pitch draws about seven pixels above its own text.

    ink_*  covers ascenders and descenders both: the box to highlight.
    cap_*  is cap-height to baseline: the box to centre on, because most UI
           strings have no descender and centring on the ink box makes them
           ride visibly high.
    """
    ink = font.getbbox("HgjQyMx")
    cap = font.getbbox("HMX")
    return {
        "line_h": sum(font.getmetrics()) / SIZE,
        "ink_top": ink[1] / SIZE,
        "ink_h": (ink[3] - ink[1]) / SIZE,
        "cap_top": cap[1] / SIZE,
        "cap_h": (cap[3] - cap[1]) / SIZE,
    }


def main():
    body, avgs = "", {}
    for name, path in FONTS.items():
        if not os.path.exists(path):
            sys.exit("no %s font at %s"
                     "\nThis measures the installed Segoe UI, so it wants a Windows"
                     " install with the interface font present. Point FONTDIR at"
                     " the directory holding segoeui.ttf if yours is elsewhere."
                     % (name, path))
        t, avg = table(name, ImageFont.truetype(path, SIZE))
        body += t + "\n"
        avgs[name] = avg

    vm = vmetrics(ImageFont.truetype(FONTS["regular"], SIZE))

    src = HEADER + body
    src += "M.avg_regular = %.4f\n" % avgs["regular"]
    src += "M.avg_bold    = %.4f\n" % avgs["bold"]
    src += "\n-- Vertical geometry as fractions of the em. See vmetrics().\n"
    for k in ("line_h", "ink_top", "ink_h", "cap_top", "cap_h"):
        src += "M.%-8s = %.4f\n" % (k, vm[k])
    src += FOOTER

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(src)
    print("wrote %s" % OUT)
    for k, v in avgs.items():
        print("  %-8s average advance %.4f em" % (k, v))
    for k in ("line_h", "ink_top", "ink_h", "cap_top", "cap_h"):
        print("  %-8s %.4f em" % (k, vm[k]))


if __name__ == "__main__":
    main()
