--[[
ui/metrics.lua -- advance widths for the panel's font, as fractions of the em.

GENERATED by tools/genmetrics.py from the installed TrueType files. Do not edit
by hand; regenerate.

Why it exists. Proportional type has no single advance number, and
`windower.text.get_extents` cannot carry layout: it only answers about a string
an object has already been given, which is a frame too late to decide how to wrap
that string, and it cannot answer at all about a string you have not drawn.

Indexed by byte, 32..126, because the panel is single-byte ASCII only: Windower's
text rendering does not handle UTF-8 multibyte. A byte outside that range falls
through the metatable to the average advance, so a stray character costs a
slightly wrong wrap and never an error.

Measured, not estimated. Segoe UI Regular averages 0.5136 em across printable
ASCII and Consolas averages 0.5498, so a monospace constant taken from Consolas
over-estimates every proportional string by about 7%. That direction only wastes
space; the units error is the one that runs text off the panel.
]]

local M = {}

M.PT_TO_PX = 96 / 72

M.regular = {
    [32]=0.2750, [33]=0.2850, [34]=0.3925, [35]=0.5900, [36]=0.5400, [37]=0.8175, [38]=0.8000, [39]=0.2300,
    [40]=0.3025, [41]=0.3025, [42]=0.4175, [43]=0.6850, [44]=0.2175, [45]=0.4000, [46]=0.2175, [47]=0.3900,
    [48]=0.5400, [49]=0.5400, [50]=0.5400, [51]=0.5400, [52]=0.5400, [53]=0.5400, [54]=0.5400, [55]=0.5400,
    [56]=0.5400, [57]=0.5400, [58]=0.2175, [59]=0.2175, [60]=0.6850, [61]=0.6850, [62]=0.6850, [63]=0.4475,
    [64]=0.9550, [65]=0.6450, [66]=0.5725, [67]=0.6200, [68]=0.7000, [69]=0.5050, [70]=0.4875, [71]=0.6850,
    [72]=0.7100, [73]=0.2650, [74]=0.3575, [75]=0.5800, [76]=0.4700, [77]=0.8975, [78]=0.7475, [79]=0.7550,
    [80]=0.5600, [81]=0.7550, [82]=0.5975, [83]=0.5325, [84]=0.5250, [85]=0.6875, [86]=0.6200, [87]=0.9350,
    [88]=0.5900, [89]=0.5525, [90]=0.5700, [91]=0.3025, [92]=0.3800, [93]=0.3025, [94]=0.6850, [95]=0.4150,
    [96]=0.2675, [97]=0.5100, [98]=0.5875, [99]=0.4625, [100]=0.5900, [101]=0.5225, [102]=0.3125, [103]=0.5900,
    [104]=0.5650, [105]=0.2425, [106]=0.2425, [107]=0.4975, [108]=0.2425, [109]=0.8625, [110]=0.5650, [111]=0.5850,
    [112]=0.5875, [113]=0.5900, [114]=0.3475, [115]=0.4250, [116]=0.3400, [117]=0.5650, [118]=0.4800, [119]=0.7225,
    [120]=0.4600, [121]=0.4850, [122]=0.4525, [123]=0.3025, [124]=0.2400, [125]=0.3025, [126]=0.6850,
}

M.bold = {
    [32]=0.2750, [33]=0.3275, [34]=0.4925, [35]=0.5925, [36]=0.5750, [37]=0.8675, [38]=0.8500, [39]=0.2925,
    [40]=0.3700, [41]=0.3700, [42]=0.4550, [43]=0.7075, [44]=0.2700, [45]=0.4050, [46]=0.2700, [47]=0.4425,
    [48]=0.5750, [49]=0.5750, [50]=0.5750, [51]=0.5750, [52]=0.5750, [53]=0.5750, [54]=0.5750, [55]=0.5750,
    [56]=0.5750, [57]=0.5750, [58]=0.2700, [59]=0.2700, [60]=0.7075, [61]=0.7075, [62]=0.7075, [63]=0.4375,
    [64]=0.9550, [65]=0.7025, [66]=0.6400, [67]=0.6250, [68]=0.7375, [69]=0.5325, [70]=0.5200, [71]=0.7100,
    [72]=0.7650, [73]=0.3175, [74]=0.4450, [75]=0.6500, [76]=0.5125, [77]=0.9575, [78]=0.7900, [79]=0.7575,
    [80]=0.6150, [81]=0.7575, [82]=0.6525, [83]=0.5600, [84]=0.5850, [85]=0.7225, [86]=0.6675, [87]=1.0050,
    [88]=0.6550, [89]=0.6075, [90]=0.6075, [91]=0.3700, [92]=0.4350, [93]=0.3700, [94]=0.7075, [95]=0.4150,
    [96]=0.3150, [97]=0.5375, [98]=0.6200, [99]=0.4800, [100]=0.6200, [101]=0.5400, [102]=0.3825, [103]=0.6200,
    [104]=0.6025, [105]=0.2850, [106]=0.2850, [107]=0.5600, [108]=0.2850, [109]=0.9150, [110]=0.6050, [111]=0.6125,
    [112]=0.6200, [113]=0.6200, [114]=0.3975, [115]=0.4400, [116]=0.3900, [117]=0.6050, [118]=0.5425, [119]=0.7975,
    [120]=0.5525, [121]=0.5375, [122]=0.4800, [123]=0.3700, [124]=0.3250, [125]=0.3700, [126]=0.7075,
}

M.avg_regular = 0.5136
M.avg_bold    = 0.5556

-- Vertical geometry as fractions of the em. See vmetrics().
M.line_h   = 1.3325
M.ink_top  = 0.3475
M.ink_h    = 0.9675
M.cap_top  = 0.3800
M.cap_h    = 0.7000

local function guard(t, avg)
    return setmetatable(t, {__index = function() return avg end})
end
guard(M.regular, M.avg_regular)
guard(M.bold, M.avg_bold)

--[[ Width of `s` in pixels at `pt` points.

     The 2% slack covers hinting. The rasteriser rounds each glyph advance to a
     whole pixel at screen sizes, and over 50 characters those roundings do not
     cancel. Over-estimating is the safe direction: it wraps a word one early,
     where under-estimating runs text off the panel. ]]
function M.width(s, pt, bold)
    if type(s) ~= 'string' or s == '' then return 0 end
    local t = bold and M.bold or M.regular
    local sum = 0
    for i = 1, #s do sum = sum + t[s:byte(i)] end
    return sum * pt * M.PT_TO_PX * 1.02
end

--[[ How many characters of `s` fit in `px`. Walks the string rather than
     dividing by an average, because "Ill" and "WWW" are not the same width. ]]
function M.fit_count(s, pt, px, bold)
    local t = bold and M.bold or M.regular
    local k = pt * M.PT_TO_PX * 1.02
    local sum, n = 0, 0
    for i = 1, #s do
        sum = sum + t[s:byte(i)] * k
        if sum > px then return n end
        n = i
    end
    return n
end

--[[ Vertical geometry in pixels at a point size.

     `set_location` places text by the top of its line box. `ink_y` is how far
     below that the glyphs actually begin and `ink_height` is how tall they are,
     and together they are the rectangle to highlight or to hit-test. Size a
     hover band from the line pitch instead and it draws about seven pixels above
     its own text. ]]
function M.ink_y(pt)      return pt * M.PT_TO_PX * M.ink_top end
function M.ink_height(pt) return pt * M.PT_TO_PX * M.ink_h end
function M.line_height(pt) return pt * M.PT_TO_PX * M.line_h end

--[[ The y to draw at so the cap box is centred in a strip of height `h` starting
     at `y`. Cap-centred rather than ink-centred: most interface strings carry no
     descender, so centring the full ink box makes them ride visibly high. ]]
function M.center_y(y, h, pt)
    local em = pt * M.PT_TO_PX
    return math.floor(y + h / 2 - (M.cap_top + M.cap_h / 2) * em + 0.5)
end

--[[ Where an underline goes: just below the descender. ]]
function M.underline_y(y, pt)
    return math.floor(y + (M.ink_top + M.ink_h) * pt * M.PT_TO_PX + 0.5)
end

return M
